services:
  fastapi:
    build: .
    container_name: marketmap-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app:ro
      - ./data:/app/data
      - /root/sources/images:/app/images:ro
